services:
  postgres:
    image: postgres:16-alpine
    container_name: hiretrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiretrack
    command: >
      postgres
      -c hba_file=/etc/postgresql/pg_hba.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - '5433:5432'

  redis:
    image: redis:7-alpine
    container_name: hiretrack-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: